/*
 * SPDX-FileCopyrightText: Copyright 2024, Arm Limited and affiliates.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*********************    Autogenerated file. DO NOT EDIT *******************
 * Generated from gen_utils.py tool file.
 * Date: 2024-08-30 18:17:01.253618
 ***************************************************************************/

#include "InputFiles.hpp"

static const char* imgFilenames[] = {
    "grace_hopper.bmp",
};

static const uint8_t* imgArrays[] = {
    im0
};

static const int imgWidths[] = {
    im0_width
};

static const int imgHeights[] = {
    im0_height
};

const char* GetFilename(const uint32_t idx)
{
    if (idx < NUMBER_OF_FILES) {
        return imgFilenames[idx];
    }
    return nullptr;
}

const uint8_t* GetImgArray(const uint32_t idx)
{
    if (idx < NUMBER_OF_FILES) {
        return imgArrays[idx];
    }
    return nullptr;
}

const uint8_t GetImgWidth(const uint32_t idx)
{
    if (idx < NUMBER_OF_FILES) {
        return imgWidths[idx];
    }
    return 0;
}

const uint8_t GetImgHeight(const uint32_t idx)
{
    if (idx < NUMBER_OF_FILES) {
        return imgHeights[idx];
    }
    return 0;
}